### ISSUE TITLE
Put the colorscheme files in `colors/` folder for plugin-install support

### ISSUE THREAD

**Issue by halostatue** [itsjunetime/rose-pine-vim#3]
Right now, I’ve had to do some post-processing to install the Rosé Pine colours because Vim only finds colourschemes in `colors/` folders. This means that if one is using `vim-plug`, `minpac` (using Vim/neovim native packages), or even the venerable `pathogen`, it’s not possible to install these colours directly.

If you move the `.vim` files to a `colors/` folder, your colorscheme will work with Vim conventions out of the box.

**Comment by itsjunetime** [comment]
Thanks for making the issue; this is fixed now with the latest commit.

**Comment by halostatue** [comment]
Thanks!
